### ISSUE TITLE
Javascript errors

### ISSUE THREAD

**Issue by JuanDBB** [methnen/m-chart-highcharts-library#12]
Hello,
I'm experiencing a javascript error with highcharts.js:

`El recurso de “***/wp-content/plugins/m-chart/components/external/highcharts/highcharts.js?ver=1.6” fue bloqueado debido a una discordancia del tipo MIME (“text/html”) (X-Content-Type-Options: nosniff)`

Do you know why I'm getting it please?

Thank you in advance

**Comment by methnen** [comment]
Hey Juan,

I had to run that through Google Translate since I don't speak Spanish. However, according to the translation, your browser is disabling the script because the server is sending it as text/html instead of javascript. My wild guess is that its possibly some sort of server configuration issue. 

I've actually never seen this error before myself.

The script is enqueued using default WordPress functionality so there's nothing unusual about how the script is being loaded by the plugin.

**Comment by JuanDBB** [comment]
Thank you ))  I will ask the people running the server.

**Comment by methnen** [comment]
If you have any more information that might point to the issue or are comfortable with me taking a look at the issue directly let me know.

Also feel free to email me directly at jamie AT methnen.com
